#!/bin/sh

for i in emacs realpath ; do
	if ! command -v $i >/dev/null 2>&1; then
		echo >&2 "'$i' not found"
		exit 1
	fi
done

[ -f "$1" ] && node="$(realpath "$1")" || node="$1"
emacs --eval '(progn (info "'"$node"'")(delete-other-windows))'
