#!/bin/sh
## Home session initialization.

if [ "$1" = "-h" ]; then
	cat <<EOF>&2
Usage: ${0##*/}

Initialize home folder.

Options:

  -u: Update Go tools.

EOF
	exit
fi

OPT_GO=""
if [ "$1" = "-u" ]; then
	OPT_GO="-u"
	shift
fi

SOURCEDIR="$HOME/personal"
[ -z "$XDG_CONFIG_HOME" ] && XDG_CONFIG_HOME="$HOME/.config"
[ -z "$XDG_DATA_HOME" ] && XDG_DATA_HOME="$HOME/.local/share"

echo "==> 'temp' folder"
mkdir -pv "$HOME/temp"

echo "==> Abook"
ln -snfv "$SOURCEDIR/contacts" "$HOME/.abook"

echo "==> Mutt"
[ -d "$SOURCEDIR/mails" ] && ln -snf "$SOURCEDIR/mails" "$XDG_DATA_HOME/mutt"
mkdir -pv "$HOME/.cache/mutt/headers"
mkdir -pv "$HOME/.cache/mutt/messages"

echo "==> Bookmarks"
mkdir -pv "$XDG_CONFIG_HOME/qutebrowser/bookmarks"
ln -sfv "$SOURCEDIR/bookmarks/bookmarks" "$XDG_CONFIG_HOME/qutebrowser/bookmarks/urls"
ln -sfv "$SOURCEDIR/bookmarks/quickmarks" "$XDG_CONFIG_HOME/qutebrowser/"

echo "==> Newsbeuter"
mkdir -pv "$XDG_DATA_HOME/newsbeuter"
ln -sfv "$SOURCEDIR/news/urls" "$XDG_CONFIG_HOME/newsbeuter/"

echo "==> Go path"
mkdir -pv "$HOME/go" "$HOME/.go-tools"
if command -v go >/dev/null 2>&1; then
	echo "==> Go extra dev tools"
	export GOPATH="$HOME/.go-tools"
	export PATH="$PATH:$GOPATH/bin"

	go get -v $OPT_GO -ldflags "-s -w" github.com/alecthomas/gometalinter && gometalinter -i $OPT_GO
	strip -s "$GOPATH"/bin/*

	## See https://dominik.honnef.co/posts/2014/12/an_incomplete_list_of_go_tools/.
	## https://dominik.honnef.co/go/
	go get -v $OPT_GO -ldflags "-s -w" \
		github.com/nsf/gocode \
		github.com/rogpeppe/godef
fi

if command -v emacs >/dev/null 2>&1; then
	echo "==> Emacs extra packages"
	yes | emacs --batch -l ~/.emacs.d/init.el --eval '(progn (package-refresh-contents)(package-install-selected-packages))'
fi
