#!/bin/sh
[ -z "$(command -v pacman)" ] && echo "You need pacman to run this script." && exit 1

sudo sh -c '
echo "[$0]"
    if [ "$0" = "sh" ]; then
        echo "Installing all .pkg.tar.xz found. Proceed? [y/N] "
        read CHOICE
        CHOICE="$(echo $CHOICE | tr [:upper:] [:lower:])"

        if [ "$CHOICE" = "y" ]; then
            for i in *; do
                echo "$i"
            done
        fi
    else
        echo "$0"
        for i; do
            echo "$i"
        done
    fi
' "$@"


