#!/bin/sh

if [ $# -eq 0 ]; then
    echo "Please give as argument build folders with .pkg.tar.xz in them."
    exit 1
fi

for i; do
    (cd "$i" && \
        rm -rfv "src" "pkg" "srcpkg" && \
        rm -fv *.pkg.tar.xz)
done
