#!/bin/sh
[ -z "$(command -v makepkg)" ] && echo "You need makepkg to run this script." && exit 1

if [ $# -eq 0 ]; then
    echo "Please give build folders as argument with .pkg.tar.xz in them."
    exit 1
fi

for i; do
    (cd "$i" && \
        mkdir -p "srcpkg" && \
        SRCDEST="srcpkg" makepkg -rscf --nocheck --noconfirm && \
        rm -rvf "srcpkg" )
done
