#!/bin/sh

[ -z "$AGENT" ] && AGENT='curl -sA "Mozilla/5.0"'

if [ "$1" = "-l" ]; then
	$AGENT 'https://www.google.com/finance/converter' \
		| awk -F'<|>|"' '/select name=from value/, /\/select/ {if ($5 != "") {sub(/\(.*\)/, "", $5); print $3, $5}}'
	exit
fi

if [ $# -lt 2 ] || [ $# -gt 3 ] || [ "$1" = "-h" ]; then
	cat <<EOF
Usage: ${0##*/} IN-CURRENCY OUT-CURRENCY VALUE
       ${0##*/} -l

Convert VALUE from IN-CURRENCY to OUT-CURRENCY.
If VALUE is not provided it is read from stdin.

CURRENCY is a 3-letters code like EUR, SEK, USD, etc.
See the list of codes with the '-l' option.

The download agent is specified from environment variable AGENT='$AGENT'.
EOF
	exit
fi

v="$3"
[ -z "$v" ] && read v
$AGENT "http://www.google.com/finance?q=$1$2" | \
	awk -v value="$v" -F '<|>' '/^1 / {print value * substr($3, 1, index($3," "))}'
