#!/bin/sh

## TODO: 'urxvt -e' does not seem to work with ftp clients.
TERMCMD=xterm

case ${DWB_SCHEME} in
    mailto)
        ! command -v xclip >/dev/null 2>&1 && exit
        echo "${DWB_URI}" | sed -e 's/mailto://' -e 's/?/ /' | xclip -i ;;
    ftp)
        ! command -v $TERMCMD >/dev/null 2>&1 && exit
        ! command -v lftp >/dev/null 2>&1 && exit
        $TERMCMD -e "lftp ${DWB_URI}";;
    *)
        ! command -v xdg-open >/dev/null 2>&1 && exit
        xdg-open "${DWB_URI}";;
esac
