#!/bin/sh

check()
{
    for i ; do
        if ! command -v $i >/dev/null 2>&1; then
            echo "'$i' not found in PATH. Exiting." >&2
            exit 1
        fi
    done
}
check emacs realpath

emacs --eval '(progn (info "'"$(realpath "$1")"'")(delete-other-windows))'
