#!/bin/sh

if [  "$1" = "-h" ]; then
	cat <<EOF>&2
Usage: ${0##*/} [FILES]

Grep non-ascii characters. If no files are provided, use stdin.

EOF
	exit
fi

perl -ne 'chomp; print $_, "\n" if /[[:^ascii:]]/' "$@"
