#!/bin/sh

if [  "$1" = "-" ] || [ "$1" = "--help" ]; then
    cat <<EOF
Usage: ${0##*/} [FILES]

Grep non-ascii characters. If no files are provided, use stdin.

EOF
    exit
fi

perl -ne 'chomp; print $_, "\n" if /[[:^ascii:]]/'
