#!/bin/sh

set -- "$HOME/.cache/awesome" \
	"$HOME/.cache/emacs/backups" \
	"$HOME/.cache/emacs/desktop" \
	"$HOME/.cache/emacs/elpa/archives" \
	"$HOME/.cache/emacs/elpa/gnupg" \
	"$HOME/.cache/emacs/emacs.bmk" \
	"$HOME/.cache/emacs/ido.last" \
	"$HOME/.cache/emacs/saveplace" \
	"$HOME/.cache/mutt" \
	"$HOME/.cache/qutebrowser" \
	"$HOME/.cache/zsh" \
	"$HOME/.cmus/autosave" \
	"$HOME/.cmus/cache" \
	"$HOME/.cmus/command-history" \
	"$HOME/.cmus/lib.pl" \
	"$HOME/.cmus/playlist.pl" \
	"$HOME/.cmus/queue.pl" \
	"$HOME/.cmus/resume" \
	"$HOME/.cmus/search-history" \
	"$HOME/.config/gtk-2.0" \
	"$HOME/.config/gtk-3.0" \
	"$HOME/.config/qutebrowser/bookmarks" \
	"$HOME/.config/qutebrowser/quickmarks" \
	"$HOME/.config/ranger/bookmarks" \
	"$HOME/.config/ranger/history" \
	"$HOME/.config/ranger/tagged" \
	"$HOME/.fehbg" \
	"$HOME/.gtk-bookmarks" \
	"$HOME/.lesshst" \
	"$HOME/.local/share/newsbeuter" \
	"$HOME/.local/share/qutebrowser" \
	"$HOME/.local/share/webkit" \
	"$HOME/.mpv/watch_later" \
	"$HOME/.mtap.fuseiso" \
	"$HOME/.pulse-cookie" \
	"$HOME/.thumbnails" \
	"$HOME/.viminfo" \
	"$HOME/.w3m" \
	"$HOME/.zcompdump"

echo "==> Files to be removed"
echo "$@" | sed 's/ /\n/g'
echo
echo "==> Files to be wiped:"
echo "Mutt passwords and ssh keys."

CHOICE="N"
echo
echo ":: Close all applications before cleaning."
echo "==> Clean home? [y/N]"
read CHOICE
case "$CHOICE" in
Y|y) ;;
*)
	echo "Nothing done."
	exit ;;
esac

echo
echo "==> Empty trash."
if ! command -v trash-empty >/dev/null 2>&1; then
	echo ":: 'trash-empty' not installed, you have to clean other drives manually."
	rm -rvf "$HOME/.local/share/Trash"
else
	trash-empty
fi

echo
echo "==> Remove dotfiles."
rm -rvf "$@"

echo
echo "==> Wipe critical data."
shred -zuv ~/.mutt.pwds.cpt
for key in ~/.ssh/*.pub; do
	shred -zuv "$key" "${key%.pub}"
done
if [ -n "$(gpg --list-secret-keys)" ]; then
	echo "WARNING: Found PGP secret keys."
fi
