#!/bin/sh
## Home session initialization.

SOURCEDIR="$HOME/dataperso"
[ -z "$XDG_CONFIG_HOME" ] && XDG_CONFIG_HOME="$HOME/.config"
[ -z "$XDG_DATA_HOME" ] && XDG_DATA_HOME="$HOME/.local/share"
[ -z "$XDG_DATA_DIRS" ] && XDG_DATA_DIRS="/usr/local/share"

echo "==> 'temp' folder"
mkdir -p "$HOME/temp"

echo "==> Abook"
ln -snf "$SOURCEDIR/contacts" "$HOME/.abook"

echo "==> Mutt"
[ -d "$SOURCEDIR/mails" ] && ln -snf "$SOURCEDIR/mails" "$HOME/.mutt.d"
mkdir -p "$HOME/.cache/mutt/headers"
mkdir -p "$HOME/.cache/mutt/messages"

echo "==> To-Do"
ln -sf "$SOURCEDIR/todo/todo.org" "$HOME/todo.org"

echo "==> Bookmarks"
if [ -z "$BROWSER" ]; then
	echo "Cannot proceed when variable BROWSER is not set."
else
	case "$BROWSER" in
	dwb)
		BOOKMARKS="$XDG_CONFIG_HOME/$BROWSER/default/"
		QUICKMARKS="$XDG_CONFIG_HOME/$BROWSER/default/" ;;
	qutebrowser)
		mkdir -p "$XDG_CONFIG_HOME/$BROWSER/bookmarks"
		BOOKMARKS="$XDG_CONFIG_HOME/$BROWSER/bookmarks/urls"
		QUICKMARKS="$XDG_CONFIG_HOME/$BROWSER/" ;;
	*)
		BOOKMARKS="$XDG_CONFIG_HOME/$BROWSER/"
		QUICKMARKS="$XDG_CONFIG_HOME/$BROWSER/" ;;
	esac
	ln -sf "$SOURCEDIR/bookmarks/bookmarks" "$BOOKMARKS"
	ln -sf "$SOURCEDIR/bookmarks/quickmarks" "$QUICKMARKS"
fi

echo "==> Newsbeuter"
mkdir -p "$XDG_DATA_HOME/newsbeuter"
ln -sf "$SOURCEDIR/news/urls" "$XDG_CONFIG_HOME/newsbeuter/"
ln -sf "$SOURCEDIR/news/news_starred" "$XDG_CONFIG_HOME/newsbeuter/"

echo "==> Launchers"
ln -snf "$SOURCEDIR/launchers" "$HOME/.launchers"

echo "==> Hackpool"
ln -snf "$SOURCEDIR/hackpool" "$HOME/.hackpool"

echo "==> Go extra dev tools"
mkdir -p "$HOME/.go"
if command -v go >/dev/null 2>&1; then
	export GOPATH=~/.go
	export PATH="$PATH:$GOPATH/bin"
	## See https://dominik.honnef.co/posts/2014/12/an_incomplete_list_of_go_tools/.
	## https://dominik.honnef.co/go/
	go get -v \
		github.com/client9/misspell \
		github.com/nsf/gocode \
		github.com/rogpeppe/godef \
		honnef.co/go/unused/cmd/unused
	go get -v github.com/alecthomas/gometalinter && gometalinter -i
	strip -s "$HOME/.go/bin"/*
fi
