#!/bin/awk -f

function usage() {
	print "Lua static checker\n\
\n\
Usage: lualint LUASOURCE\n\
\n\
Blah"
}

BEGIN {
	globals["assert"] = 1
	globals["collectgarbage"] = 1
	globals["dofile"] = 1
	globals["error"] = 1
	globals["_G"] = 1
	globals["getfenv"] = 1
	globals["getmetatable"] = 1
	globals["ipairs"] = 1
	globals["load"] = 1
	globals["loadfile"] = 1
	globals["loadstring"] = 1
	globals["next"] = 1
	globals["pairs"] = 1
	globals["pcall"] = 1
	globals["print"] = 1
	globals["rawequal"] = 1
	globals["rawget"] = 1
	globals["rawset"] = 1
	globals["select"] = 1
	globals["setfenv"] = 1
	globals["setmetatable"] = 1
	globals["tonumber"] = 1
	globals["tostring"] = 1
	globals["type"] = 1
	globals["unpack"] = 1
	globals["_VERSION"] = 1
	globals["xpcall"] = 1

	globals["module"] = 1
	globals["package"] = 1
	globals["require"] = 1

	globals["coroutine"] = 1
	globals["debug"] = 1
	globals["io"] = 1
	globals["math"] = 1
	globals["os"] = 1
	globals["string"] = 1
	globals["table"] = 1

	while ( ("luac -p -l -- " ARGV[1] " && find . -type f -exec md5sum {} +" | getline ) > 0) {
		if ($0 ~ /ETTABUP.*_ENV/) {
			field = substr($NF, 2, length($NF)-2)
			if (!globals[field]) {
				if ($3 == "GETTABUP") {
					op = "<-"
				} else {
					op = "->"
				}
				print($2, op, field)
			}
		}
	}
}
