#!/bin/sh

_printhelp()
{
    cat <<EOF
Usage: ${1##*/} [OPTIONS] PACKAGES
       ${1##*/} -a [OPTIONS]

Display package size. Output contains no double and is alphabetically sorted. A
grand total is printed at the end. It will only work for repos packages by
default.

  -a: All installed packages.
  -h: Show this help.
  -n: Output is sorted by name.
  -q: Uses installed packages database instead of repos database. It speeds up
      queries and allows displaying size of local packages not available in
      repos.
  -s: Output is sorted by size.
  -t: Print total.

EOF
}

CMD="S"
TOTAL_SIZE=0
OPT_SORT=false
OPT_ALL=false
OPT_TOTAL=0

while getopts ":ahnqst" opt; do
    case $opt in
        a)
            OPT_ALL=true
            CMD="Q" ;;
        h)
            _printhelp "$0"
            exit 1 ;;
        n)
            OPT_SORT="sort -uk3" ;;
        q)
            CMD="Q" ;;
        s)
            OPT_SORT="sort -n" ;;
        t)
            OPT_TOTAL=1 ;;
        ?)
            _printhelp "$0"
            exit 1 ;;
        :)
            echo "Missing argument."
            _printhelp "$0"
            exit 1 ;;
    esac
done

shift $(($OPTIND - 1))

## If expac is available, use it since it is much faster.
if ! command -v expac >/dev/null; then
    expac -HK -$CMD '%6m %n' "$@" | awk -v sum=$OPT_TOTAL '{sub(/[\.,]00/,""); if(sum) total+=$1; printf("%6s %s %s\n",$1,$2,$3)} END {if(sum) print total, "KiB TOTAL"}' | ($OPT_SORT || cat)
    exit
fi

if $OPT_ALL; then
    ## All-packages mode. We use a different algorithm which is much faster than for a list of packages.
    DBPath=$(awk -F = '/^ *DBPath/{print $2}' /etc/pacman.conf)
    [ ! -d "$DBPath" ] && DBPath="/var/lib/pacman/"

    awk -v sum=$OPT_TOTAL '/^%NAME%/ {getline;pkg=$0} /^%SIZE%/ {getline; size=$0/1024; if (sum) total+=size; printf("%6s KiB %s\n", size, pkg)} END {if (sum) print total, "KiB TOTAL"}' "$DBPath"/local/*/desc | ($OPT_SORT || cat)
    exit
fi

## Per-package mode
if [ $# -eq 0 ]; then
    echo "Missing argument."
    _printhelp "$0"
    exit 1
fi

if [ -f "${0%/*}/.pacman-init" ];then
    . "${0%/*}/.pacman-init"
else
    echo "Missing init file" >&2 && exit 1
fi

if [ $(pacman -Qq "$@" 2>/dev/null | wc -l) -eq 0 ]; then
    echo "No valid package given." >&2
    exit
fi

## We use external variable for awk to fit current locales. In the following
## command, we strip the decimals. This makes output lighter. The line below
## does not do it.
#   '$0 ~ pkg {pkgname=$2} $0 ~ filter {printf("%13s %s\n", $2, pkgname)}'
pacman -${CMD}i "$@" | awk -F ": " -v filter="$pacman_size" -v pkgname="$pacman_name" -v sum=$OPT_TOTAL \
'$0 ~ pkgname {pkg=$2} $0 ~ filter {gsub(/[\.,].*/,""); if(sum) total+=$2; printf("%6s KiB %s\n", $2, pkg)} END {if(sum) print total, "KiB TOTAL"}' | ($OPT_SORT || cat)
