#!/bin/sh

if [ $# -ne 2 ]; then
    echo "Usage: ${0##*/} INPUT OUTPUT"
    echo "Resize input PDF to an A4 output PDF."
    exit
fi

gs  -q -o "$2" -sDEVICE=pdfwrite -sPAPERSIZE=a4 -dFIXEDMEDIA -dPDFFitPage -dCompatibilityLevel=1.4 "$1"

