#!/bin/sh

usage () {
	cat <<EOF>&2
Usage: ${0##*/} PROCESS-EXP

Extended pgrep -a.

EOF
}

[ $# -eq 0 ] && usage && exit 1
[ "$1" = "-h" ] && usage && exit
[ "$1" = "--" ] && shift

for i ; do
	## We need to store the result of 'ps' first to prevent the filtering from
	## appearing in the result.
	BUF="$(ps aux)"
	echo "$BUF" | awk -v pid=$$ -v pattern="$i" '$2 != pid && $0 ~ pattern'
done
