#!/bin/sh

## Create lists of system- and TeX Live packages.

## Variables
PKG_ROOT="$HOME/.pkglists"
mkdir -p "$PKG_ROOT"

## Arch Linux
if command -v pacman >/dev/null 2>&1; then
	pacman -Qneq | sort >"$PKG_ROOT/arch-official"
	pacman -Qmeq | sort >"$PKG_ROOT/arch-aur"
fi

## FreeBSD
if [ "$(uname)" = "FreeBSD" ]; then
	pkg_info | cut -f1 -d' ' >"$PKG_ROOT/freebsd"
fi

## TeXlive
if command -v tlmgr >/dev/null 2>&1; then
	tlctl l >"$PKG_ROOT/texlive"
fi
