#!/bin/sh

usage () {
	cat <<EOF>&2
Usage: ${0##*/} [OPTIONS] STRING [FILES]

Prepend STRING to FILES or stdin if unspecified. STRING may not contain pipes
('|').

Options:

  -i: If files are provided, convert them in-place.

EOF
}

[ $# -eq 0 ] && usage && exit 1
[ "$1" = "-h" ] && usage && exit
[ "$1" = "--" ] && shift

unset OPT
if [ "$1" = "-i" ]; then
	OPT=-i
	shift
fi

VAR="$1"
shift

sed $OPT "1i$VAR" "$@"
