#!/bin/sh

if [ "$#" -eq 0 ] || [ "$1" = "-h" ]; then
	cat<<EOF
Usage: ${1##*/} FILE
       ${1##*/} ENTRIES FILE

Run ffprobe on FILE using shell print format. If no entry is specified, print
format and streams.

EOF
	exit
fi


if [ $# -gt 1 ]; then
	ffprobe -v quiet -print_format flat=s=_ -show_entries "$@"
else
	ffprobe -v quiet -print_format flat=s=_ -show_format -show_streams "$1"
fi
