#!/bin/sh
## This is a compatibility wrapper for 'realpath'.

if command -v greadlink >/dev/null; then
    ## On BSD systems, we might have greadlink
    greadlink -f "$@"
elif command -v readlink >/dev/null && [ "$(uname)" = "Linux" ]; then
    readlink -f "$@"
else
    ## Dirty fallback
    echo "$@"
fi
