#!/bin/sh

_printhelp ()
{
    cat<<EOF
Usage: ${0##*/} [OPTIONS] SEARCH REPLACE [FILES]

Replace SEARCH by REPLACE in FILES. If no file is provided, use stdin.

Options:

  -i:  Replace file content instead of printing to stdout.
  -h:  Show this help.

EOF
}

OPT_INPLACE=""
while getopts ":ih" opt; do
    case $opt in
        i)
            OPT_INPLACE=-i ;;
        h)
            _printhelp "$0"
            exit 1 ;;
        ?)
            _printhelp "$0"
            exit 1 ;;
        :)
            _printhelp "$0"
            exit 1 ;;
    esac
done

shift $(($OPTIND - 1))

if [ $# -lt 2 ]; then
    _printhelp "$0"
    exit 1
fi

search="$1"
replace="$2"
shift 2

_replace()
{
    awk -v search="$search" -v replace="$replace" '{gsub(search, replace); print}' "$@"
}

if [ $# -eq 0 ] || [ -z "$OPT_INPLACE" ]; then
    _replace "$@"
else
    for i ; do
        out="$(mktemp "$i.XXXXXX")"
        _replace "$i" > "$out"
        mv "$out" "$i"
    done
fi
