#!/bin/sh

opt_dry="-n"
if [ "$1" = "-p" ]; then
	opt_dry=""
	shift
fi

if [ "$1" = "-h" ] || [ $# -ne 2 ]; then
	cat<<EOF
Usage: ${0##*/} SOURCE DEST

Use rsync to mirror SOURCE to DEST while showing progress and allowing resuming.
SOURCE does not need to be ending with a trailing slash. Only size is used for
comparison.

A dry-run is made by default.

Options:

  -p: Process.

EOF

	exit
fi

rsync $opt_dry -livr --size-only --delete-excluded --append-verify --progress -- "$1"/ "$2"
