#!/bin/sh

if [ "$1" = "-h" ] || [ $# -ne 2 ]; then
    cat<<EOF
Usage: ${0##*/} FOLDER1 FOLDER2

Dry-run of rsync over two folders.

EOF

    exit
fi

rsync -nivr --size-only --delete-excluded "$1"/ "$2"
