#!/bin/sh

if [ "$1" = "-h" ]; then
	cat <<EOF>&2
Usage: ${0##*/}

Clean various running processes. Run it before exiting a session.

EOF
	exit
fi

if command -v emacsclient >/dev/null 2>&1; then
	if emacsclient -e '(kill-emacs)' >/dev/null 2>&1; then
		echo >&2 "Emacs terminated."
	fi
fi
if [ -S "$SSH_AUTH_SOCK" ]; then
	eval "$(ssh-agent -k)"
	echo >&2 "SSH agent terminated."
fi
