#!/bin/sh

if [ $# -eq 0 ] || [ "$1" = "-h" ]; then
	cat<<EOF
Usage: ${0##*/} FOLDERS

Check for files containing common mispelling:

- "\`" and "´" instead of "'",
- "oe" instead of "œ".
EOF
fi

if ! command -v recode >/dev/null 2>&1; then
	echo >&2 "recode needed."
	exit 1
fi

for i ; do
	while IFS= read -r j; do
		echo -n "# "
		file "$j"
		grep -m1 "\`" "$j"
		grep -m1 "´"  "$j"
		grep -m1 "oe" "$j"
	done <<EOF
$(find "$i" -type f -size -50M -print)
EOF
done
