#!/bin/sh

[ -z "$VIEWER" ] && VIEWER="zathura --fork"

for i; do
	if $(file -i -b "$i" | grep -qi 'pdf\|postscript\|djvu'); then
		$VIEWER "$i"
	else
		## The drawback of reading from stdin is that zathura will not save the
		## position.
		acat "$i" | $VIEWER -
	fi
done
