;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-semi&comma
        kill-region
        c-electric-delete-forward
        dabbrev-expand
        repeat
        yas/expand
        ))

(setq mc/cmds-to-run-once
      '(
        c-compile
        ))
